<?php include __DIR__ . '/inc/header.phtml'; ?>
<div class="container sub-page">
    <div class="row">
        <div class="col-md-9">
            <h2 class="orange pad-bottom">Development</h2>
            <p>Being an open source project, Pop PHP welcomes input and collaboration from the community and maintains
                an open dialogue with the community. Pull requests or issues can be submitted to the appropriate
                repository on <a href="https://github.com/popphp" target="_blank">Github</a>. Additional support and
                communication is maintained on the <a href="https://discord.gg/8DUdCr9x" target="_blank">Discord
                server</a> and on <a href="https://twitter.com/popphpframework" target="_blank">Twitter</a>.</p>
            <p>Any developers can submit issues or pull requests on GitHub under the related repository and start a
                dialogue to discuss what needs to, or should be done to the code in the repository. Or, simply email the project
                directly by clicking the email icon below. The goal is have the overall project benefit and be improved
                from community-driven support.</p>
            <hr/>
            <div class="sm-btn-block">
                <a href="https://github.com/popphp" class="btn btn-md btn-orange-solid" target="_blank"><i class="fa fa-lg fa-github"></i> GitHub</a>
                <a href="https://discord.gg/8DUdCr9x" class="btn btn-md btn-orange-solid" target="_blank"><i class="fa fa-comments"></i> Discord</a>
                <a href="https://twitter.com/popphpframework" class="btn btn-md btn-orange-solid" target="_blank"><i class="fa fa-twitter"></i> Twitter</a>
                <a href="#" class="btn btn-md btn-orange-solid email-link" target="_blank"><i class="fa fa-envelope"></i> Email</a>
            </div>
            <hr/>
            <h3>Report an Issue</h3>
            <h4 class="no-transform font-normal">...or Request a Feature</h4>
            <p>If you found an issue with something, or simply want to request a new or enhanced feature, first check
                the component's issue tracker to see if an issue has already been opened to address the same thing. All
                issues are submitted and managed under the <strong>Issues</strong> tab for each respective component. Free
                free to discuss the issue in the main <a href="https://gitter.im/pop-php-framework/Lobby" target="_blank">Gitter</a>
                chat room with others. If you're ready to submit an issue, then go ahead and do so. When submitting the issue,
                please provide a clear and concise test case where the issue has occurred, or in the case of a feature request,
                please provide sample code of the idea or concept.</p>
            <hr/>
            <h3>Contribute</h3>
            <p>Contributions from other developers are most welcomed, and anyone can contribute in a number of ways, whether
               it's improving or patching the existing code base, adding new features or simply helping with the documentation.
               Everything is hosted on <a href="https://github.com/popphp" target="_blank">GitHub</a>, so when you're ready
               to contribute, simply fork the component's repository and work on it locally. Commit your work and push it
               back to your forked version on GitHub. Then send a <strong>pull request</strong> for your changes to be reviewed
               and included in the master repository.</p>
        </div>
        <div class="col-md-3 side-col">
<?php include __DIR__ . '/inc/side-nav.phtml'; ?>
        </div>
    </div>
</div>
<?php include __DIR__ . '/inc/footer.phtml'; ?>
