<?php include __DIR__ . '/inc/header.phtml'; ?>
<div class="container sub-page">
    <div class="row">
        <div class="col-md-9">
            <h2 class="orange pad-bottom">Development</h2>
            <p>Being an open source project, Pop PHP welcomes input and collaboration from the community and maintains
                an open dialogue with the community. Pull requests or issues can be submitted to the appropriate
                repository on <a href="https://github.com/popphp" target="_blank">Github</a>. Additional support and
                communication is maintained in the <a href="https://gitter.im/pop-php-framework/Lobby" target="_blank">Gitter
                    chat room</a> and on <a href="https://twitter.com/popphpframework" target="_blank">Twitter</a>.</p>
            <p>Any developers can submit issues or pull requests on GitHub under the related repository and start a
                dialogue on what needs to, or should be done to the code in the repository. Or, simply email the project
                directly by clicking the email icon below. The goal is have the overall project benefit and be improved
                from community-driven support.</p>
            <hr/>
            <div class="sm-btn-block">
                <a href="https://github.com/popphp" class="btn btn-outline btn-sm btn-orange" target="_blank"><i class="fa fa-github"></i> GitHub</a>
                <a href="https://gitter.im/pop-php-framework/Lobby" class="btn btn-outline btn-sm btn-orange" target="_blank"><i class="fa fa-comments"></i> Gitter</a>
                <a href="https://twitter.com/popphpframework" class="btn btn-outline btn-sm btn-orange" target="_blank"><i class="fa fa-twitter"></i> Twitter</a>
                <a href="#" class="btn btn-outline btn-sm btn-orange email-link" target="_blank"><i class="fa fa-envelope"></i> Email</a>
            </div>
            <hr/>
        </div>
        <div class="col-md-3 side-col">
<?php include __DIR__ . '/inc/side-nav.phtml'; ?>
        </div>
    </div>
</div>
<?php include __DIR__ . '/inc/footer.phtml'; ?>
