<?php include __DIR__ . '/inc/header.phtml'; ?>
<div id="top" class="container mx-auto pt-12 pb-12 pr-20 pl-20 max-[1280px]:pl-10 max-[1280px]:pr-10 max-[768px]:pl-0 max-[768px]:pr-0">
    <div class="grid grid-cols-1 lg:grid-cols-4 mx-auto">
        <div class="col-span-3 main-content">
            <h2 class="font-alt font-bold text-3xl text-orange-700 uppercase pb-8">Documentation</h2>
            <p class="pb-4">The Pop PHP Framework contains a group of core components and an additional 30+ components that serve as a
                toolkit for rapid application development. Provided in the links below are full documentation complete
                with examples and tutorials, as well as a straight forward API documentation for those interested in
                learning the framework more in depth. As the documentation outlines, the framework and each of its
                components are available via <a href="https://getcomposer.org/" class="text-orange-700 hover:underline" target="_blank">Composer</a> or the
                standalone download links on this website.</p>
            <p class="pb-4">Those that wish to contribute to any of the components or the documentation, please visit the <a
                    href="/development" class="text-orange-700 hover:underline">development page</a> to find out how to do so.</p>
            <hr class="mt-4 mb-4" />
            <p class="pb-4"><strong>Full Documentation:</strong></p>
            <ul class="list-disc ml-12 mb-4">
                <li class="mb-1"><a class="text-orange-700 hover:underline" href="http://docs.popphp.org/" target="_blank">v<?=substr($version, 0, strpos($version, '.')); ?>.x</a></li>
                <li class="mb-1"><a class="text-orange-700 hover:underline" href="https://pop-php-framework.readthedocs.io/en/latest/" target="_blank">Legacy</a> (<= v4.8.0)</li>
            </ul>
            <hr class="mt-4 mb-4" />
            <p class="pb-4"><strong>API Documentation:</strong></p>
            <ul class="list-disc ml-12 mb-4">
                <li class="mb-1"><a class="text-orange-700 hover:underline" href="https://api.popphp.org/6.x/" target="_blank">v<?=substr($version, 0, strpos($version, '.')); ?>.x</a></li>
                <li class="mb-1"><a class="text-orange-700 hover:underline" href="https://api.popphp.org/4.8/" target="_blank">v4.8.0</a></li>
                <li class="mb-1"><a class="text-orange-700 hover:underline" href="https://api.popphp.org/4.7/" target="_blank">v4.7.0</a></li>
                <li class="mb-1"><a class="text-orange-700 hover:underline" href="https://api.popphp.org/4.5/" target="_blank">v4.5.0</a></li>
                <li class="mb-1"><a class="text-orange-700 hover:underline" href="https://api.popphp.org/4.0/" target="_blank">v4.0.0</a></li>
            </ul>
            <hr class="mt-4 mb-4" />
            <p class="pb-4"><strong>Code coverage</strong> documentation is available for review <a class="text-orange-700 hover:underline" href="https://cc.popphp.org/" target="_blank">here</a>.</p>
            <p class="pb-4">The <strong>changelog</strong> documentation is available <a class="text-orange-700 hover:underline" href="https://docs.popphp.org/changelog" target="_blank">here</a>.</p>
            <hr class="mt-4 mb-4" />
            <p class="pb-4"><strong>Tutorial Application</strong></p>
            <p class="pb-4">There is a small tutorial application, <code class="inline-code">popphp/popphp-tutorial</code>, available to outline the basic foundation of an application built using the Pop PHP Framework.
                You can get it on <a class="text-orange-700 hover:underline" href="https://github.com/popphp/popphp-tutorial" target="_blank">GitHub</a>.</p>
            <hr class="mt-4 mb-4" />
            <div class="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div class="rounded-md border border-solid border-gray-300 pb-2 text-center">
                    <h6 class="text-sm font-bold pt-2 pb-2 mb-4 border-b border-solid border-gray-300">popphp/popphp</h6>
                    <a href="https://github.com/popphp/popphp" class="github-icon inline-block text-gray-500 text-center rounded-md border-2 border-solid border-gray-500 hover:text-white hover:bg-gray-500 hover:border-gray-500" target="_blank"><span class="relative inline-block top-0.5">GitHub</span></a>
                </div>
                <div class="rounded-md border border-solid border-gray-300 pb-2 text-center">
                    <h6 class="text-sm font-bold pt-2 pb-2 mb-4 border-b border-solid border-gray-300">popphp/popcorn</h6>
                    <a href="https://github.com/popphp/popcorn" class="github-icon inline-block text-gray-500 text-center rounded-md border-2 border-solid border-gray-500 hover:text-white hover:bg-gray-500 hover:border-gray-500" target="_blank"><span class="relative inline-block top-0.5">GitHub</span></a>
                </div>
                <div class="rounded-md border border-solid border-gray-300 pb-2 text-center">
                    <h6 class="text-sm font-bold pt-2 pb-2 mb-4 border-b border-solid border-gray-300">popphp/pop-acl</h6>
                    <a href="https://github.com/popphp/pop-acl" class="github-icon inline-block text-gray-500 text-center rounded-md border-2 border-solid border-gray-500 hover:text-white hover:bg-gray-500 hover:border-gray-500" target="_blank"><span class="relative inline-block top-0.5">GitHub</span></a>
                </div>
                <div class="rounded-md border border-solid border-gray-300 pb-2 text-center">
                    <h6 class="text-sm font-bold pt-2 pb-2 mb-4 border-b border-solid border-gray-300">popphp/pop-audit</h6>
                    <a href="https://github.com/popphp/pop-audit" class="github-icon inline-block text-gray-500 text-center rounded-md border-2 border-solid border-gray-500 hover:text-white hover:bg-gray-500 hover:border-gray-500" target="_blank"><span class="relative inline-block top-0.5">GitHub</span></a>
                </div>
                <div class="rounded-md border border-solid border-gray-300 pb-2 text-center">
                    <h6 class="text-sm font-bold pt-2 pb-2 mb-4 border-b border-solid border-gray-300">popphp/pop-auth</h6>
                    <a href="https://github.com/popphp/pop-auth" class="github-icon inline-block text-gray-500 text-center rounded-md border-2 border-solid border-gray-500 hover:text-white hover:bg-gray-500 hover:border-gray-500" target="_blank"><span class="relative inline-block top-0.5">GitHub</span></a>
                </div>
                <div class="rounded-md border border-solid border-gray-300 pb-2 text-center">
                    <h6 class="text-sm font-bold pt-2 pb-2 mb-4 border-b border-solid border-gray-300">popphp/pop-cache</h6>
                    <a href="https://github.com/popphp/pop-cache" class="github-icon inline-block text-gray-500 text-center rounded-md border-2 border-solid border-gray-500 hover:text-white hover:bg-gray-500 hover:border-gray-500" target="_blank"><span class="relative inline-block top-0.5">GitHub</span></a>
                </div>
                <div class="rounded-md border border-solid border-gray-300 pb-2 text-center">
                    <h6 class="text-sm font-bold pt-2 pb-2 mb-4 border-b border-solid border-gray-300">popphp/pop-code</h6>
                    <a href="https://github.com/popphp/pop-code" class="github-icon inline-block text-gray-500 text-center rounded-md border-2 border-solid border-gray-500 hover:text-white hover:bg-gray-500 hover:border-gray-500" target="_blank"><span class="relative inline-block top-0.5">GitHub</span></a>
                </div>
                <div class="rounded-md border border-solid border-gray-300 pb-2 text-center">
                    <h6 class="text-sm font-bold pt-2 pb-2 mb-4 border-b border-solid border-gray-300">popphp/pop-color</h6>
                    <a href="https://github.com/popphp/pop-color" class="github-icon inline-block text-gray-500 text-center rounded-md border-2 border-solid border-gray-500 hover:text-white hover:bg-gray-500 hover:border-gray-500" target="_blank"><span class="relative inline-block top-0.5">GitHub</span></a>
                </div>
                <div class="rounded-md border border-solid border-gray-300 pb-2 text-center">
                    <h6 class="text-sm font-bold pt-2 pb-2 mb-4 border-b border-solid border-gray-300">popphp/pop-config</h6>
                    <a href="https://github.com/popphp/pop-config" class="github-icon inline-block text-gray-500 text-center rounded-md border-2 border-solid border-gray-500 hover:text-white hover:bg-gray-500 hover:border-gray-500" target="_blank"><span class="relative inline-block top-0.5">GitHub</span></a>
                </div>
                <div class="rounded-md border border-solid border-gray-300 pb-2 text-center">
                    <h6 class="text-sm font-bold pt-2 pb-2 mb-4 border-b border-solid border-gray-300">popphp/pop-console</h6>
                    <a href="https://github.com/popphp/pop-console" class="github-icon inline-block text-gray-500 text-center rounded-md border-2 border-solid border-gray-500 hover:text-white hover:bg-gray-500 hover:border-gray-500" target="_blank"><span class="relative inline-block top-0.5">GitHub</span></a>
                </div>
                <div class="rounded-md border border-solid border-gray-300 pb-2 text-center">
                    <h6 class="text-sm font-bold pt-2 pb-2 mb-4 border-b border-solid border-gray-300">popphp/pop-cookie</h6>
                    <a href="https://github.com/popphp/pop-cookie" class="github-icon inline-block text-gray-500 text-center rounded-md border-2 border-solid border-gray-500 hover:text-white hover:bg-gray-500 hover:border-gray-500" target="_blank"><span class="relative inline-block top-0.5">GitHub</span></a>
                </div>
                <div class="rounded-md border border-solid border-gray-300 pb-2 text-center">
                    <h6 class="text-sm font-bold pt-2 pb-2 mb-4 border-b border-solid border-gray-300">popphp/pop-crypt</h6>
                    <a href="https://github.com/popphp/pop-crypt" class="github-icon inline-block text-gray-500 text-center rounded-md border-2 border-solid border-gray-500 hover:text-white hover:bg-gray-500 hover:border-gray-500" target="_blank"><span class="relative inline-block top-0.5">GitHub</span></a>
                </div>
                <div class="rounded-md border border-solid border-gray-300 pb-2 text-center">
                    <h6 class="text-sm font-bold pt-2 pb-2 mb-4 border-b border-solid border-gray-300">popphp/pop-css</h6>
                    <a href="https://github.com/popphp/pop-css" class="github-icon inline-block text-gray-500 text-center rounded-md border-2 border-solid border-gray-500 hover:text-white hover:bg-gray-500 hover:border-gray-500" target="_blank"><span class="relative inline-block top-0.5">GitHub</span></a>
                </div>
                <div class="rounded-md border border-solid border-gray-300 pb-2 text-center">
                    <h6 class="text-sm font-bold pt-2 pb-2 mb-4 border-b border-solid border-gray-300">popphp/pop-csv</h6>
                    <a href="https://github.com/popphp/pop-csv" class="github-icon inline-block text-gray-500 text-center rounded-md border-2 border-solid border-gray-500 hover:text-white hover:bg-gray-500 hover:border-gray-500" target="_blank"><span class="relative inline-block top-0.5">GitHub</span></a>
                </div>
                <div class="rounded-md border border-solid border-gray-300 pb-2 text-center">
                    <h6 class="text-sm font-bold pt-2 pb-2 mb-4 border-b border-solid border-gray-300">popphp/pop-db</h6>
                    <a href="https://github.com/popphp/pop-db" class="github-icon inline-block text-gray-500 text-center rounded-md border-2 border-solid border-gray-500 hover:text-white hover:bg-gray-500 hover:border-gray-500" target="_blank"><span class="relative inline-block top-0.5">GitHub</span></a>
                </div>
                <div class="rounded-md border border-solid border-gray-300 pb-2 text-center">
                    <h6 class="text-sm font-bold pt-2 pb-2 mb-4 border-b border-solid border-gray-300">popphp/pop-debug</h6>
                    <a href="https://github.com/popphp/pop-debug" class="github-icon inline-block text-gray-500 text-center rounded-md border-2 border-solid border-gray-500 hover:text-white hover:bg-gray-500 hover:border-gray-500" target="_blank"><span class="relative inline-block top-0.5">GitHub</span></a>
                </div>
                <div class="rounded-md border border-solid border-gray-300 pb-2 text-center">
                    <h6 class="text-sm font-bold pt-2 pb-2 mb-4 border-b border-solid border-gray-300">popphp/pop-dir</h6>
                    <a href="https://github.com/popphp/pop-dir" class="github-icon inline-block text-gray-500 text-center rounded-md border-2 border-solid border-gray-500 hover:text-white hover:bg-gray-500 hover:border-gray-500" target="_blank"><span class="relative inline-block top-0.5">GitHub</span></a>
                </div>
                <div class="rounded-md border border-solid border-gray-300 pb-2 text-center">
                    <h6 class="text-sm font-bold pt-2 pb-2 mb-4 border-b border-solid border-gray-300">popphp/pop-dom</h6>
                    <a href="https://github.com/popphp/pop-dom" class="github-icon inline-block text-gray-500 text-center rounded-md border-2 border-solid border-gray-500 hover:text-white hover:bg-gray-500 hover:border-gray-500" target="_blank"><span class="relative inline-block top-0.5">GitHub</span></a>
                </div>
                <div class="rounded-md border border-solid border-gray-300 pb-2 text-center">
                    <h6 class="text-sm font-bold pt-2 pb-2 mb-4 border-b border-solid border-gray-300">popphp/pop-filter</h6>
                    <a href="https://github.com/popphp/pop-filter" class="github-icon inline-block text-gray-500 text-center rounded-md border-2 border-solid border-gray-500 hover:text-white hover:bg-gray-500 hover:border-gray-500" target="_blank"><span class="relative inline-block top-0.5">GitHub</span></a>
                </div>
                <div class="rounded-md border border-solid border-gray-300 pb-2 text-center">
                    <h6 class="text-sm font-bold pt-2 pb-2 mb-4 border-b border-solid border-gray-300">popphp/pop-form</h6>
                    <a href="https://github.com/popphp/pop-form" class="github-icon inline-block text-gray-500 text-center rounded-md border-2 border-solid border-gray-500 hover:text-white hover:bg-gray-500 hover:border-gray-500" target="_blank"><span class="relative inline-block top-0.5">GitHub</span></a>
                </div>
                <div class="rounded-md border border-solid border-gray-300 pb-2 text-center">
                    <h6 class="text-sm font-bold pt-2 pb-2 mb-4 border-b border-solid border-gray-300">popphp/pop-ftp</h6>
                    <a href="https://github.com/popphp/pop-ftp" class="github-icon inline-block text-gray-500 text-center rounded-md border-2 border-solid border-gray-500 hover:text-white hover:bg-gray-500 hover:border-gray-500" target="_blank"><span class="relative inline-block top-0.5">GitHub</span></a>
                </div>
                <div class="rounded-md border border-solid border-gray-300 pb-2 text-center">
                    <h6 class="text-sm font-bold pt-2 pb-2 mb-4 border-b border-solid border-gray-300">popphp/pop-http</h6>
                    <a href="https://github.com/popphp/pop-http" class="github-icon inline-block text-gray-500 text-center rounded-md border-2 border-solid border-gray-500 hover:text-white hover:bg-gray-500 hover:border-gray-500" target="_blank"><span class="relative inline-block top-0.5">GitHub</span></a>
                </div>
                <div class="rounded-md border border-solid border-gray-300 pb-2 text-center">
                    <h6 class="text-sm font-bold pt-2 pb-2 mb-4 border-b border-solid border-gray-300">popphp/pop-i18n</h6>
                    <a href="https://github.com/popphp/pop-i18n" class="github-icon inline-block text-gray-500 text-center rounded-md border-2 border-solid border-gray-500 hover:text-white hover:bg-gray-500 hover:border-gray-500" target="_blank"><span class="relative inline-block top-0.5">GitHub</span></a>
                </div>
                <div class="rounded-md border border-solid border-gray-300 pb-2 text-center">
                    <h6 class="text-sm font-bold pt-2 pb-2 mb-4 border-b border-solid border-gray-300">popphp/pop-image</h6>
                    <a href="https://github.com/popphp/pop-image" class="github-icon inline-block text-gray-500 text-center rounded-md border-2 border-solid border-gray-500 hover:text-white hover:bg-gray-500 hover:border-gray-500" target="_blank"><span class="relative inline-block top-0.5">GitHub</span></a>
                </div>
                <div class="rounded-md border border-solid border-gray-300 pb-2 text-center">
                    <h6 class="text-sm font-bold pt-2 pb-2 mb-4 border-b border-solid border-gray-300">popphp/pop-kettle</h6>
                    <a href="https://github.com/popphp/pop-kettle" class="github-icon inline-block text-gray-500 text-center rounded-md border-2 border-solid border-gray-500 hover:text-white hover:bg-gray-500 hover:border-gray-500" target="_blank"><span class="relative inline-block top-0.5">GitHub</span></a>
                </div>
                <div class="rounded-md border border-solid border-gray-300 pb-2 text-center">
                    <h6 class="text-sm font-bold pt-2 pb-2 mb-4 border-b border-solid border-gray-300">popphp/pop-log</h6>
                    <a href="https://github.com/popphp/pop-log" class="github-icon inline-block text-gray-500 text-center rounded-md border-2 border-solid border-gray-500 hover:text-white hover:bg-gray-500 hover:border-gray-500" target="_blank"><span class="relative inline-block top-0.5">GitHub</span></a>
                </div>
                <div class="rounded-md border border-solid border-gray-300 pb-2 text-center">
                    <h6 class="text-sm font-bold pt-2 pb-2 mb-4 border-b border-solid border-gray-300">popphp/pop-mail</h6>
                    <a href="https://github.com/popphp/pop-mail" class="github-icon inline-block text-gray-500 text-center rounded-md border-2 border-solid border-gray-500 hover:text-white hover:bg-gray-500 hover:border-gray-500" target="_blank"><span class="relative inline-block top-0.5">GitHub</span></a>
                </div>
                <div class="rounded-md border border-solid border-gray-300 pb-2 text-center">
                    <h6 class="text-sm font-bold pt-2 pb-2 mb-4 border-b border-solid border-gray-300">popphp/pop-mime</h6>
                    <a href="https://github.com/popphp/pop-mime" class="github-icon inline-block text-gray-500 text-center rounded-md border-2 border-solid border-gray-500 hover:text-white hover:bg-gray-500 hover:border-gray-500" target="_blank"><span class="relative inline-block top-0.5">GitHub</span></a>
                </div>
                <div class="rounded-md border border-solid border-gray-300 pb-2 text-center">
                    <h6 class="text-sm font-bold pt-2 pb-2 mb-4 border-b border-solid border-gray-300">popphp/pop-nav</h6>
                    <a href="https://github.com/popphp/pop-nav" class="github-icon inline-block text-gray-500 text-center rounded-md border-2 border-solid border-gray-500 hover:text-white hover:bg-gray-500 hover:border-gray-500" target="_blank"><span class="relative inline-block top-0.5">GitHub</span></a>
                </div>
                <div class="rounded-md border border-solid border-gray-300 pb-2 text-center">
                    <h6 class="text-sm font-bold pt-2 pb-2 mb-4 border-b border-solid border-gray-300">popphp/pop-paginator</h6>
                    <a href="https://github.com/popphp/pop-paginator" class="github-icon inline-block text-gray-500 text-center rounded-md border-2 border-solid border-gray-500 hover:text-white hover:bg-gray-500 hover:border-gray-500" target="_blank"><span class="relative inline-block top-0.5">GitHub</span></a>
                </div>
                <div class="rounded-md border border-solid border-gray-300 pb-2 text-center">
                    <h6 class="text-sm font-bold pt-2 pb-2 mb-4 border-b border-solid border-gray-300">popphp/pop-pdf</h6>
                    <a href="https://github.com/popphp/pop-pdf" class="github-icon inline-block text-gray-500 text-center rounded-md border-2 border-solid border-gray-500 hover:text-white hover:bg-gray-500 hover:border-gray-500" target="_blank"><span class="relative inline-block top-0.5">GitHub</span></a>
                </div>
                <div class="rounded-md border border-solid border-gray-300 pb-2 text-center">
                    <h6 class="text-sm font-bold pt-2 pb-2 mb-4 border-b border-solid border-gray-300">popphp/pop-queue</h6>
                    <a href="https://github.com/popphp/pop-queue" class="github-icon inline-block text-gray-500 text-center rounded-md border-2 border-solid border-gray-500 hover:text-white hover:bg-gray-500 hover:border-gray-500" target="_blank"><span class="relative inline-block top-0.5">GitHub</span></a>
                </div>
                <div class="rounded-md border border-solid border-gray-300 pb-2 text-center">
                    <h6 class="text-sm font-bold pt-2 pb-2 mb-4 border-b border-solid border-gray-300">popphp/pop-session</h6>
                    <a href="https://github.com/popphp/pop-session" class="github-icon inline-block text-gray-500 text-center rounded-md border-2 border-solid border-gray-500 hover:text-white hover:bg-gray-500 hover:border-gray-500" target="_blank"><span class="relative inline-block top-0.5">GitHub</span></a>
                </div>
                <div class="rounded-md border border-solid border-gray-300 pb-2 text-center">
                    <h6 class="text-sm font-bold pt-2 pb-2 mb-4 border-b border-solid border-gray-300">popphp/pop-storage</h6>
                    <a href="https://github.com/popphp/pop-storage" class="github-icon inline-block text-gray-500 text-center rounded-md border-2 border-solid border-gray-500 hover:text-white hover:bg-gray-500 hover:border-gray-500" target="_blank"><span class="relative inline-block top-0.5">GitHub</span></a>
                </div>
                <div class="rounded-md border border-solid border-gray-300 pb-2 text-center">
                    <h6 class="text-sm font-bold pt-2 pb-2 mb-4 border-b border-solid border-gray-300">popphp/pop-utils</h6>
                    <a href="https://github.com/popphp/pop-utils" class="github-icon inline-block text-gray-500 text-center rounded-md border-2 border-solid border-gray-500 hover:text-white hover:bg-gray-500 hover:border-gray-500" target="_blank"><span class="relative inline-block top-0.5">GitHub</span></a>
                </div>
                <div class="rounded-md border border-solid border-gray-300 pb-2 text-center">
                    <h6 class="text-sm font-bold pt-2 pb-2 mb-4 border-b border-solid border-gray-300">popphp/pop-validator</h6>
                    <a href="https://github.com/popphp/pop-validator" class="github-icon inline-block text-gray-500 text-center rounded-md border-2 border-solid border-gray-500 hover:text-white hover:bg-gray-500 hover:border-gray-500" target="_blank"><span class="relative inline-block top-0.5">GitHub</span></a>
                </div>
                <div class="rounded-md border border-solid border-gray-300 pb-2 text-center">
                    <h6 class="text-sm font-bold pt-2 pb-2 mb-4 border-b border-solid border-gray-300">popphp/pop-view</h6>
                    <a href="https://github.com/popphp/pop-view" class="github-icon inline-block text-gray-500 text-center rounded-md border-2 border-solid border-gray-500 hover:text-white hover:bg-gray-500 hover:border-gray-500" target="_blank"><span class="relative inline-block top-0.5">GitHub</span></a>
                </div>
            </div>
            <hr class="mt-4 mb-4" />
        </div>
        <div class="col-span-1 mx-auto">
<?php include __DIR__ . '/inc/side-nav.phtml'; ?>
        </div>
    </div>
</div>
<?php include __DIR__ . '/inc/footer.phtml'; ?>
