<?php include __DIR__ . '/inc/header.phtml'; ?>
<div class="container sub-page">
    <div class="row">
        <div class="col-md-9">
            <h2 class="orange pad-bottom">Documentation</h2>
            <p>The Pop PHP Framework contains a group of core components and an additional 26 components that serve as a
                toolkit for rapid application development. Provided in the links below are full documentation complete
                with examples and tutorials, as well as a straight forward API documentation for those interested in
                learning the framework more in depth. As the documentation outlines, the framework and each of its
                components are available via <a href="https://getcomposer.org/" target="_blank">Composer</a> or the
                standalone download links on this website.</p>
            <p>Those that wish to contribute to any of the components or the documentation, please visit the <a
                    href="/development.html">development page</a> to find out how to do so.</p>
            <hr/>
            <p><strong>Full Documentation:</strong></p>
            <ul>
                <li><a href="http://docs.popphp.org/en/latest/" target="_blank">v3.6.0</a></li>
                <li><a href="http://docs.popphp.org/en/v3.0.0/" target="_blank">v3.0.0</a></li>
                <li><a href="http://docs.popphp.org/en/v2.1.1/" target="_blank">v2.1.1</a></li>
            </ul>
            <hr/>
            <p><strong>API Documentation:</strong></p>
            <ul>
                <li><a href="http://api.popphp.org/3.6/" target="_blank">v3.6</a></li>
                <li><a href="http://api.popphp.org/3.0/" target="_blank">v3.0</a></li>
                <li><a href="http://api.popphp.org/2.1/" target="_blank">v2.1</a></li>
            </ul>
            <hr/>
        </div>
        <div class="col-md-3 side-col">
<?php include __DIR__ . '/inc/side-nav.phtml'; ?>
        </div>
    </div>
</div>
<?php include __DIR__ . '/inc/footer.phtml'; ?>
