<?php include __DIR__ . '/inc/header.phtml'; ?>
<div id="top" class="container mx-auto pt-12 pb-12 pr-20 pl-20 max-[1280px]:pl-10 max-[1280px]:pr-10 max-[768px]:pl-0 max-[768px]:pr-0">
    <div class="grid grid-cols-1 lg:grid-cols-4 gap-8 mx-auto">
        <div class="col-span-3">
            <h2 class="font-alt font-bold text-3xl text-red-500 uppercase pb-8"><?=$response['code']; ?> : <?=$response['message']; ?></h2>
            <p>Sorry, that page that does not exist.</p>
        </div>
        <div>
        </div>
    </div>
</div>
<?php include __DIR__ . '/inc/footer.phtml'; ?>
