<?php include __DIR__ . '/inc/header.phtml'; ?>
<div class="container sub-page">
    <div class="row">
        <div class="col-md-9">
            <h2 class="error pad-bottom"><?=$response['code']; ?> : <?=$response['message']; ?></h2>
            <p>Sorry, that page that does not exist.</p>
        </div>
        <div class="col-md-3 side-col">
        </div>
    </div>
</div>
<?php include __DIR__ . '/inc/footer.phtml'; ?>
