<?php include __DIR__ . '/inc/header.phtml'; ?>
<div id="top" class="container mx-auto pr-20 pl-20 max-[1280px]:pl-10 max-[1280px]:pr-10 max-[768px]:pl-0 max-[768px]:pr-0">
    <div class="grid grid-cols-1 lg:grid-cols-4 gap-4 mx-auto">
        <div class="col-span-3">
            <h2 class="error pad-bottom">Error</h2>
            <p><?=$message; ?></p>
        </div>
        <div>
        </div>
    </div>
</div>
<?php include __DIR__ . '/inc/footer.phtml'; ?>
