<?php include __DIR__ . '/inc/header.phtml'; ?>
<!-- Header -->
<header class="masthead">
    <div class="container">
        <div class="home-logo"></div>
        <div class="intro-text">
            <span class="skills">Version <?=$version; ?> Now Available</span>
            <div class="text-center sm-btn-block">
                <a href="https://github.com/popphp/popphp-framework" class="btn btn-md btn-outline" target="_blank">
                    <i class="fa fa-lg fa-github"></i>
                    <span class="smaller-text">GitHub</span>
                </a>
                <a href="/assets/downloads/popphp-php-framework-<?=$version; ?>.zip" class="btn btn-lg btn-outline"
                   target="_blank" onclick="ga('send', 'event', 'file', 'download', 'Download Pop PHP v3.6 ZIP');">
                    <i class="fa fa-download"></i>
                    <span class="smaller-text">zip</span><?php if (!empty($zip)): ?> <span class="bytes"><?=$zip; ?></span><?php endif; ?>
                </a>
                <a href="/assets/downloads/popphp-php-framework-<?=$version; ?>.tar.gz" class="btn btn-lg btn-outline"
                   target="_blank" onclick="ga('send', 'event', 'file', 'download', 'Download Pop PHP v3.6 TGZ');">
                    <i class="fa fa-download"></i>
                    <span class="smaller-text">gz</span><?php if (!empty($tgz)): ?> <span class="bytes"><?=$tgz; ?></span><?php endif; ?>
                </a>
                <a href="/assets/downloads/popphp-php-framework-<?=$version; ?>.tar.bz2" class="btn btn-lg btn-outline"
                   target="_blank" onclick="ga('send', 'event', 'file', 'download', 'Download Pop PHP v3.6 TBZ2');">
                    <i class="fa fa-download"></i>
                    <span class="smaller-text">bz2</span><?php if (!empty($tbz)): ?> <span class="bytes"><?=$tbz; ?></span><?php endif; ?>
                </a>
            </div>
        </div>
    </div>
</header>

<!-- Portfolio Grid Section -->
<section id="portfolio">
    <div class="container">
        <h2 class="text-center dark-blue">Featured Components</h2>
        <hr class="star-primary">
        <div class="row">
            <div class="col-sm-4">
                <div class="portfolio-link">
                    <div class="portfolio-image">
                        <i class="fa fa-database fa-3x light-gray"></i>
                        <h3>pop-db</h3>
                        <p>A robust database abstraction component with many features, including Active Record, SQL
                            abstraction and migrations</p>
                        <p class="pad-top-alt">
                            <a href="https://github.com/popphp/pop-db" class="btn btn-sm btn-outline-secondary"
                               target="_blank"><i class="fa fa-lg fa-github"></i> GitHub</a>
                            <a href="http://docs.popphp.org/en/latest/reference/pop_db.html"
                               class="btn btn-sm btn-outline-secondary" target="_blank"><i class="fa fa-file-text"></i>
                                Docs</a>
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="portfolio-link">
                    <div class="portfolio-image">
                        <i class="fa fa-exchange fa-3x light-gray"></i>
                        <h3>pop-http</h3>
                        <p>An HTTP component that includes support for handling HTTP requests and responses, file
                            uploads and HTTP clients.</p>
                        <p class="pad-top-alt">
                            <a href="https://github.com/popphp/pop-http" class="btn btn-sm btn-outline-secondary"
                               target="_blank"><i class="fa fa-lg fa-github"></i> GitHub</a>
                            <a href="http://docs.popphp.org/en/latest/reference/pop_http.html"
                               class="btn btn-sm btn-outline-secondary" target="_blank"><i class="fa fa-file-text"></i>
                                Docs</a>
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="portfolio-link">
                    <div class="portfolio-image">
                        <i class="fa fa-wpforms fa-3x light-gray"></i>
                        <h3>pop-form</h3>
                        <p>A feature-rich HTML form component that makes creating, generating and validating HTML forms
                            simple.</p>
                        <p class="pad-top-alt">
                            <a href="https://github.com/popphp/pop-form" class="btn btn-sm btn-outline-secondary"
                               target="_blank"><i class="fa fa-lg fa-github"></i> GitHub</a>
                            <a href="http://docs.popphp.org/en/latest/reference/pop_form.html"
                               class="btn btn-sm btn-outline-secondary" target="_blank"><i class="fa fa-file-text"></i>
                                Docs</a>
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="portfolio-link">
                    <div class="portfolio-image">
                        <i class="fa fa-file-pdf-o fa-3x light-gray"></i>
                        <h3>pop-pdf</h3>
                        <p>A PDF component that can create and generate PDF files from scratch, or by importing other
                            PDF files.</p>
                        <p class="pad-top-alt">
                            <a href="https://github.com/popphp/pop-pdf" class="btn btn-sm btn-outline-secondary"
                               target="_blank"><i class="fa fa-lg fa-github"></i> GitHub</a>
                            <a href="http://docs.popphp.org/en/latest/reference/pop_pdf.html"
                               class="btn btn-sm btn-outline-secondary" target="_blank"><i class="fa fa-file-text"></i>
                                Docs</a>
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="portfolio-link">
                    <div class="portfolio-image">
                        <i class="fa fa-image fa-3x light-gray"></i>
                        <h3>pop-image</h3>
                        <p>An image component that supports creating, editing and manipulating images via common PHP
                            image extensions.</p>
                        <p class="pad-top-alt">
                            <a href="https://github.com/popphp/pop-image" class="btn btn-sm btn-outline-secondary"
                               target="_blank"><i class="fa fa-lg fa-github"></i> GitHub</a>
                            <a href="http://docs.popphp.org/en/latest/reference/pop_image.html"
                               class="btn btn-sm btn-outline-secondary" target="_blank"><i class="fa fa-file-text"></i>
                                Docs</a>
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="portfolio-link">
                    <div class="portfolio-image">
                        <i class="fa fa-envelope fa-3x light-gray"></i>
                        <h3>pop-mail</h3>
                        <p>A mail component that supports sending mail via SMTP and mail queues, as well receiving mail
                            via an IMAP or POP client.</p>
                        <p class="pad-top-alt">
                            <a href="https://github.com/popphp/pop-mail" class="btn btn-sm btn-outline-secondary"
                               target="_blank"><i class="fa fa-lg fa-github"></i> GitHub</a>
                            <a href="http://docs.popphp.org/en/latest/reference/pop_mail.html"
                               class="btn btn-sm btn-outline-secondary" target="_blank"><i class="fa fa-file-text"></i>
                                Docs</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<a name="about"></a>
<!-- About Section -->
<section class="success" id="about">
    <div class="container">
        <h2 class="text-center">About</h2>
        <hr class="star-light">
        <div class="row">
            <div class="col-lg-4 ml-auto">
                <p>Pop PHP is an open source, object-oriented PHP framework with humble beginnings dating back to 2009,
                    where it started as a small library of components. The first official version of Pop was released in
                    early 2012. Version 2 was release in 2014, and version 3 is the current live version in production.</p>
            </div>
            <div class="col-lg-4 mr-auto">
                <p>The focus of Pop is to provide a robust set of lightweight tools to assist developers with rapid
                    application development. With a relatively small learning curve, Pop aims to help developers in
                    getting the features they need into their applications so they can be up and running quickly.</p>
            </div>
            <div class="col-lg-8 mx-auto text-center">
                <a href="http://docs.popphp.org/" class="btn btn-lg btn-outline" target="_blank">
                    <i class="fa fa-file-text"></i>
                    Docs
                </a>
                <a href="https://api.popphp.org/3.6/" class="btn btn-lg btn-outline" target="_blank">
                    <i class="fa fa-code"></i>
                    API
                </a>
            </div>
        </div>
    </div>
</section>
<a name="popcorn"></a>
<!-- Popcorn Section -->
<section id="contact">
    <div class="container">
        <h3 class="dark-blue text-center">Looking for something even lighter?</h3>
        <img class="img-centered img-block" src="/assets/img/popcorn-logo-shadow.png" width="240" height="240" alt="">
        <p class="text-center one-p">Popcorn is available as a micro-framework layer that can be utilized to build REST
            applications and APIs. It utilizes only a few of the web-based components, although any of the other
            components can be added at any time. With Popcorn, a developer can enforce routing rules based on request
            methods and quickly wire up a REST-based application.</p>
        <div class="col-lg-8 mx-auto text-center sm-btn-block">
            <a href="https://github.com/popphp/popcorn" class="btn btn-md btn-outline-secondary" target="_blank"><i
                    class="fa fa-lg fa-github"></i> GitHub</a>
            <a href="http://docs.popphp.org/en/latest/user_guide/popcorn.html" class="btn btn-md btn-outline-secondary"
               target="_blank"><i class="fa fa-file-text"></i> Docs</a>
            <a href="https://api.popphp.org/3.6/namespaces/Popcorn.html" class="btn btn-md btn-outline-secondary"
               target="_blank"><i class="fa fa-code"></i> API</a>
            <a href="/overview#popcorn" class="btn btn-md btn-outline-secondary" target="_blank">Learn More <i
                        class="fa fa-angle-double-right"></i></a>
        </div>
    </div>
</section>

<?php include __DIR__ . '/inc/footer.phtml'; ?>
