<?php include __DIR__ . '/inc/header.phtml'; ?>
<a name="top"></a>
<div class="container sub-page">
    <div class="row">
        <div class="col-md-9">
            <h2 class="orange pad-bottom">Overview</h2>
            <p>The Pop PHP Framework is a lightweight, yet robust PHP framework that can be used for rapid application development. The framework itself has a base set of core components as well as numerous other additional components to facilitate many of the common features needed for a PHP application.</p>
            <p>The two main concepts behind the Pop PHP Framework have always been:</p>
            <ol>
                <li>To be easy to use and lightweight</li>
                <li>To promote standards in development while maintaining a manageable learning curve</li>
            </ol>
            <p>The goal is so that anyone from an advanced programmer to a novice developer can install and start using the Pop PHP Framework quickly and effectively.</p>
            <hr />
            <h3 class="dark-blue pad-bottom">Requirements</h3>
            <p>The Pop PHP Framework has been built for and tested with <strong>PHP 7</strong>, but also works with <strong>PHP 5.6</strong> at this time. So the only true requirement is that to have at least <strong>PHP 5.6</strong> installed in the environment.</p>
            <a name="installation"></a>
            <p>For more on the various additional recommended server components, settings and extensions, please review <a href="http://docs.popphp.org/en/latest/installation.html#requirements" target="_blank">the documentation</a>.</p>
            <hr />
            <h3 class="dark-blue pad-bottom">Installation</h3>
            <p>The Pop PHP Framework provides a number of options to install as much or as little as a developer
                requires. It can be installed in a few of different ways:</p>
            <a name="full"></a>
            <ul>
                <li><a href="#full">Full Installation</a></li>
                <li><a href="#barebones">Barebones Installation</a></li>
                <li><a href="#popcorn">Popcorn Installation</a></li>
                <li><a href="#individual">Installing Individual Components</a></li>
            </ul>
            <hr/>
            <p><strong>Full Installation:</strong></p>
            <p>A developer can install or download the full framework, which includes the core components plus an
                additional 26 components to serve as a toolkit for application development. The full version can either
                be downloaded from one of the links on this website, or installed via <a href="https://getcomposer.org/"
                                                                                         target="_blank">Composer</a>
                like this:</p>
            <div class="code-div"><code>$ composer create-project popphp/popphp-framework project-folder</code></div>
            <p class="pad-top">Or, it can be added to a project like this:</p>
            <div class="code-div"><code>$ composer require popphp/popphp-framework</code></div>
            <p class="pad-top">Or, it can be added to a project's <code>composer.json</code> file like this:</p>
            <a name="barebones"></a>
            <div class="code-div"><code>{
    "require": {
        "popphp/popphp-framework": ">=3.6.0"
    }
}</code></div>
            <p class="small-p">[ <a href="#installation"><i class="fa fa-angle-double-up"></i> Top</a> ]</p>
            <hr/>
            <p><strong>Barebones Installation:</strong></p>
            <p>A developer can opt to only install the barebones core components that make up the foundation of the
                application stack. This includes:</p>
            <ul>
                <li>The Application Object</li>
                <li>The Router</li>
                <li>The Service Locator</li>
                <li>The Event Manager</li>
                <li>The Module Manager</li>
                <li>The Base Controller Class</li>
            </ul>
            <p>The barebones version can be installed using one of the methods above, but by swapping out the framework
                repository for the core repository like this:</p>
            <a name="popcorn"></a>
            <div class="code-div"><code>{
    "require": {
        "popphp/popphp": ">=3.1.0"
    }
}</code></div>
            <p class="small-p">[ <a href="#installation"><i class="fa fa-angle-double-up"></i> Top</a> ]</p>
            <hr/>
            <p><strong>Popcorn Installation:</strong></p>
            <p>A developer can also opt to install Popcorn, which is a web-based, micro-framework layer that can be
                utilized to build REST applications and APIs. It installs the same core components from the barebones
                installation, plus the <code>popphp/pop-http</code>, <code>popphp/pop-session</code> and <code>popphp/pop-view</code>
                components.</p>
            <p>Popcorn can be installed using one of the methods above, but by using the Popcorn repository like
                this:</p>
            <a name="individual"></a>
            <div class="code-div"><code>{
    "require": {
        "popphp/popcorn": ">=3.1.0"
    }
}</code></div>
            <p class="small-p">[ <a href="#installation"><i class="fa fa-angle-double-up"></i> Top</a> ]</p>
            <hr/>
            <p><strong>Installing Individual Components:</strong></p>
            <p>And finally, if a developer has chosen a different framework or application stack in which to build an
                application, the individual components of the Pop PHP Framework play nicely with others. Please refer to
                the individual documentation of whichever components are required to be added to your project to get the
                name of the repository for those components.</p>
            <p class="small-p">[ <a href="#installation"><i class="fa fa-angle-double-up"></i> Top</a> ]</p>
            <hr/>
        </div>
        <div class="col-md-3 side-col">
<?php include __DIR__ . '/inc/side-nav.phtml'; ?>
        </div>
    </div>
</div>
<?php include __DIR__ . '/inc/footer.phtml'; ?>
