<!-- Footer -->
<footer class="w-full pt-12 pb-12 bg-gray-700 text-white">
    <div class="container mx-auto text-center">
        <ul class="social-nav">
            <li>
                <a class="btn-social" href="https://github.com/popphp" target="_blank" title="GitHub">
                    <img class="relative mt-2 mr-auto ml-auto" src="/assets/img/github-mark-white.png" width="32" />
                </a>
            </li>
            <li>
                <a class="btn-social" href="https://popphp.slack.com/" target="_blank" title="Slack">
                    <img class="relative mt-2 mr-auto ml-auto" src="/assets/img/slack-logo.png" width="32" />
                </a>
            </li>
            <li>
                <a class="btn-social" href="https://discord.gg/TZjgT74U7E" target="_blank" title="Discord">
                    <img class="relative mt-3 mr-auto ml-auto" src="/assets/img/discord-mark-white.png" width="32" />
                </a>
            </li>
            <li>
                <a class="btn-social" href="https://x.com/popphpframework" target="_blank" title="x.com">
                    <img class="relative mt-2 mr-auto ml-auto" src="/assets/img/x-logo-white.png" width="26" />
                </a>
            </li>
        </ul>
    </div>
    <div class="container mx-auto text-center pt-16">
        Copyright &copy; 2009-<?=date('Y'); ?> NOLA Interactive. All Rights Reserved.
    </div>
</footer>
</body>

</html>
