<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="keywords" content="pop php, pop php framework, php framework, lightweight php framework, php" />
    <meta name="description" content="Pop PHP Framework is a lightweight, yet feature-rich PHP framework." />
    <meta name="author" content="Pop PHP Framework" />
    <meta name="robots" content="all" />
    <meta property="og:image" content="https://www.popphp.org/assets/img/popphp-thumb.jpg" />
    <meta property="og:title" content="Pop PHP Framework" />
    <meta property="og:description" content="A lightweight, yet feature-rich PHP framework." />

    <title><?=$title; ?> : Pop PHP Framework : A lightweight, yet feature-rich PHP framework.</title>

    <link rel="stylesheet" href="https://rsms.me/inter/inter.css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="/assets/app.css">
    <link type="image/png" rel="shortcut icon" href="/assets/img/pop-php-icon.png" />
    <script defer src="/assets/app.js"></script>

    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-7TX6XKNXSL"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-7TX6XKNXSL');
    </script>

</head>

<body class="text-gray-900 antialiased">
<?php include __DIR__ . '/nav.phtml'; ?>
