<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="keywords" content="pop php, pop php framework, php framework, lightweight php framework, php" />
    <meta name="description" content="Pop PHP Framework is a lightweight, yet feature-rich PHP framework." />
    <meta name="author" content="Pop PHP Framework" />
    <meta name="robots" content="all" />
    <meta property="og:image" content="https://www.popphp.org/assets/img/popphp-thumb.jpg" />
    <meta property="og:title" content="Pop PHP Framework" />
    <meta property="og:description" content="A lightweight, yet feature-rich PHP framework." />

    <title><?=$title; ?> : Pop PHP Framework : A lightweight, yet feature-rich PHP framework.</title>

    <!-- Bootstrap core CSS -->
    <link href="/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />

    <!-- Custom fonts for this template -->
    <link href="/assets/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />

    <!-- Custom styles for this template -->
    <link href="/assets/css/freelancer.min.css" rel="stylesheet" type="text/css" />
    <link type="image/png" rel="shortcut icon" href="/assets/img/pop-php-icon.png" />

    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-7TX6XKNXSL"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-7TX6XKNXSL');
    </script>

</head>

<body id="page-top">
<?php include __DIR__ . '/nav.phtml'; ?>
