<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="keywords" content="pop php, pop php framework, php framework, lightweight php framework, php" />
    <meta name="description" content="Pop PHP Framework is a lightweight, yet feature-rich PHP framework." />
    <meta name="author" content="Pop PHP Framework" />
    <meta name="robots" content="all" />

    <title><?=$title; ?> : Pop PHP Framework : A lightweight, yet feature-rich PHP framework.</title>

    <!-- Bootstrap core CSS -->
    <link href="/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />

    <!-- Custom fonts for this template -->
    <link href="/assets/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />

    <!-- Custom styles for this template -->
    <link href="/assets/css/freelancer.min.css" rel="stylesheet" type="text/css" />
    <link type="image/png" rel="shortcut icon" href="/assets/img/pop-php-icon.png" />

    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-53872942-7', 'auto');
        ga('send', 'pageview');
    </script>

</head>

<body id="page-top">
<?php include __DIR__ . '/nav.phtml'; ?>
