            <h5 class="font-normal no-transform">Latest Documentation</h5>
            <div>
                <a href="http://docs.popphp.org/" class="btn btn-md btn-block btn-outline btn-orange"
                   target="_blank">
                    <i class="fa fa-file-text"></i> Docs
                </a>
                <a href="http://api.popphp.org/3.6/" class="btn btn-md btn-block btn-outline btn-orange"
                   target="_blank">
                    <i class="fa fa-code"></i> API
                </a>
            </div>
            <hr />
            <h5 class="font-normal no-transform">Get Latest Version 3.6.0</h5>
            <div>
                <a href="https://github.com/popphp/popphp-framework" class="btn btn-md btn-block btn-outline btn-orange"
                   target="_blank">
                    <i class="fa fa-github"></i>
                    GitHub
                </a>
                <a href="/assets/downloads/popphp-php-framework-3.6.0.zip"
                   class="btn btn-md btn-block btn-outline btn-orange" target="_blank"
                   onclick="ga('send', 'event', 'file', 'download', 'Download Pop PHP v3.6 ZIP');">
                    <i class="fa fa-download"></i>
                    zip
                </a>
                <a href="/assets/downloads/popphp-php-framework-3.6.0.tar.gz"
                   class="btn btn-md btn-block btn-outline btn-orange" target="_blank"
                   onclick="ga('send', 'event', 'file', 'download', 'Download Pop PHP v3.6 TGZ');">
                    <i class="fa fa-download"></i>
                    gz
                </a>
                <a href="/assets/downloads/popphp-php-framework-3.6.0.tar.bz2"
                   class="btn btn-md btn-block btn-outline btn-orange" target="_blank"
                   onclick="ga('send', 'event', 'file', 'download', 'Download Pop PHP v3.6 TBZ2');">
                    <i class="fa fa-download"></i>
                    bz2
                </a>
            </div>
