            <h5 class="font-normal no-transform">Latest Documentation</h5>
            <div>
                <a href="http://docs.popphp.org/" class="btn btn-md btn-block btn-outline btn-orange"
                   target="_blank">
                    <i class="fa fa-file-text"></i> <span class="smaller-text">Docs</span>
                </a>
                <a href="https://api.popphp.org/4.7/" class="btn btn-md btn-block btn-outline btn-orange"
                   target="_blank">
                    <i class="fa fa-code"></i> <span class="smaller-text">API</span>
                </a>
            </div>
            <hr />
            <h5 class="font-normal no-transform">Get Latest Version <?=$version; ?></h5>
            <div>
                <a href="https://github.com/popphp/popphp-framework" class="btn btn-md btn-block btn-outline btn-orange"
                   target="_blank">
                    <i class="fa fa-lg fa-github"></i>
                    <span class="smaller-text">GitHub</span>
                </a>
            </div>
            <div class="changelog-btn">
                <a href="https://pop-php-framework.readthedocs.io/en/latest/changelog.html" target="_blank"><i class="fa fa-code-fork"></i> <span class="smaller-text">Changelog</span></a>
            </div>
